### PR TITLE
Remove validate password input

### PR DESCRIPTION
**Pull request by peterjaap**

### CODE REVIEW

**Comment by peterjaap** [comment]
@mitelg woops, fixed

**Comment by peterjaap** [comment]
Ugh why can't we just follow the state of the PR here?

**Comment by mitelg** [comment]
for our internal workflow we need a jira ticket. 

if something missing in your PR, you will get a message from us. otherwise you will get a message, that your PR got merged :wink: 

we cannot update the status we have in the ticket to every PR

**Comment by King-of-Babylon** [comment]
Hi @peterjaap ,
thank you for your contribution. Your change was merged in the following commit: https://github.com/shopwareLabs/SwagMigrationMagento/commit/de46d1db409ae28bfad665765b5cb23358f5e2bb

**Pull request closed without merging**
